name: BlockProtector
main: BlockProtector\Main
version: 1.1
api: 3.0.0-ALPHA12

load: POSTWORLD
author: luca28pet
description: Log all block changes in your worlds
website: https://github.com/luca28pet/BlockProtector
commands:
 blockprotector:
  description: Activate inspector
  usage: "/bp <inspect>"
  aliases: [bp, bprotect]
  permission: blockprotector.command
permissions:
 blockprotector.command:
  description: "Allows to use the inspector"
  default: op
